#!/usr/bin/env python3
"""
Bazzite Sunshine Manager

Author: wadiebs
Date: January 2026
Version: 2.0

Description:
Automated importer and manager for Sunshine streaming app configurations.
This tool recreates Sunshine's apps.json with proper structure and organization.

Features:
- Automatic detection of Sunshine configuration directory (Flatpak + native)
- Imports applications from multiple sources (Steam, Heroic Launcher, custom launchers)
- Maintains proper JSON structure with "env" section first, followed by "apps"
- Comprehensive environment variable and application mapping
- Blacklist support for filtering unwanted applications
- Modular architecture for easy extension of import sources
- Support for poster/thumbnail artwork organization
"""

import sys
import os
import json
import re
import shutil
import pathlib
from pathlib import Path
from typing import Dict, Any

VERSION = "2.0"

# Safe to import local modules now
from common.utils import log, read_json, write_json  # noqa: E402
from common.reconcile import (MARKER, backup, log_plan, plan_document,  # noqa: E402
                              reconcile)
from importers.steam import import_steam  # noqa: E402
from importers.heroic import import_heroic  # noqa: E402
from importers.launchers import import_launchers

def detect_sunshine_config_dir(home: str) -> str:
    """Detect Sunshine config directory (Flatpak + native)."""
    flatpak_ids = ["dev.lizardbyte.app.Sunshine", "dev.lizardbyte.Sunshine"]
    for fid in flatpak_ids:
        fp_dir = os.path.join(home, ".var", "app", fid, "config", "sunshine")
        if os.path.isdir(fp_dir):
            return fp_dir
    return os.path.join(home, ".config", "sunshine")


def getenv_flag(name: str, default: bool) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return str(val).strip().lower() in ("1", "true", "yes", "on")


def main(argv: list[str]) -> int:
    dry_run = getenv_flag("BSM_DRY_RUN", False)
    as_json = getenv_flag("BSM_JSON", False)
    home = str(Path.home())
    conf_dir = detect_sunshine_config_dir(home)
    os.makedirs(conf_dir, exist_ok=True)

    # Paths
    apps_json = os.path.join(conf_dir, "apps.json")
    images_root = os.path.join(conf_dir, "images")
    images_dir_steam = os.path.join(images_root, "steam")
    images_dir_heroic = os.path.join(images_root, "heroic")
    images_dir_sideload = os.path.join(images_root, "sideload")
    for d in (images_dir_steam, images_dir_heroic, images_dir_sideload):
        os.makedirs(d, exist_ok=True)

    log(f"Sunshine config: {conf_dir}")
    log(f"Images root:     {images_root}")

    # Load what is already there. Entries we did not generate are preserved.
    payload = read_json(apps_json, {})
    if not isinstance(payload, dict):
        payload = {"apps": payload if isinstance(payload, list) else []}
    existing_apps = payload.get("apps")
    if not isinstance(existing_apps, list):
        existing_apps = []

    # Files written by older versions of this tool have no ownership markers, but
    # were a wholesale rewrite, so every entry in them is ours. Adopt by name.
    meta = payload.get("meta")
    adopt_by_name = (
        isinstance(meta, dict)
        and meta.get("generated-by") == "bazzite-sunshine-manager"
        and not any(isinstance(a, dict) and MARKER in a for a in existing_apps)
    )
    if adopt_by_name:
        log("Existing apps.json was generated by an older version; adopting entries by name.")

    refresh = [t for t in re.split(r"[,\s]+", os.getenv("BSM_REFRESH_EDITED", "").strip()) if t]
    if refresh:
        log(f"Refreshing user-edited fields for: {', '.join(refresh)}")

    # Read toggles from environment
    IMPORT_STEAM = getenv_flag("IMPORT_STEAM", True)
    IMPORT_HEROIC = getenv_flag("IMPORT_HEROIC", True)

    enabled_importers = []
    if IMPORT_STEAM:
        enabled_importers.append("steam")
    if IMPORT_HEROIC:
        enabled_importers.append("heroic")

    settings: Dict[str, Any] = dict(os.environ)

    # Collect apps from enabled importers, recording how each one fared. A source
    # that raised is not the same as a source that found nothing, and consumers
    # need to tell them apart before acting on "missing" entries.
    apps: list = []
    sources: list = []

    def run_source(name: str, enabled: bool, fn):
        if not enabled:
            log(f"{name.capitalize()} importer disabled.")
            sources.append({"name": name, "enabled": False, "status": "disabled", "imported": 0})
            return
        try:
            found = fn() or []
        except Exception as e:                       # noqa: BLE001 - reported, not swallowed
            log(f"{name.capitalize()} importer failed: {e}")
            sources.append({"name": name, "enabled": True, "status": "error",
                            "error": str(e), "imported": 0})
            return
        apps.extend(found)
        sources.append({"name": name, "enabled": True, "status": "ok", "imported": len(found)})

    run_source("steam", IMPORT_STEAM,
               lambda: import_steam(home, conf_dir, images_dir_steam, settings))
    run_source("heroic", IMPORT_HEROIC,
               lambda: import_heroic(home, conf_dir, images_dir_heroic, settings))
    run_source("launcher", True,
               lambda: import_launchers(home, conf_dir,
                                        os.path.join(conf_dir, "images", "launchers"), settings))

    # --- ENV BLOCK FIRST ---
    # Default PATH augmentation as requested; allow optional extra append via ENV_PATH_APPEND.
    env_block = {
        "PATH": "$(PATH):$(HOME)/.local/bin" + ((":" + os.getenv("ENV_PATH_APPEND")) if os.getenv("ENV_PATH_APPEND") else "")
    }

    merged_apps, plan = reconcile(existing_apps, apps,
                                  adopt_by_name=adopt_by_name, refresh=refresh)
    log_plan(plan)

    if dry_run:
        log("Dry run: apps.json not written.")
    elif os.path.exists(apps_json):
        try:
            log(f"Backup saved: {backup(apps_json)}")
        except Exception as e:
            log(f"Warning: failed to backup apps.json: {e}")

    # "env" first, then "apps", preserving any other top-level keys the user has.
    out = {"env": payload.get("env", env_block), "apps": merged_apps}
    for key, value in payload.items():
        if key not in ("env", "apps", "meta"):
            out[key] = value
    out["meta"] = {
        "generated-by": "bazzite-sunshine-manager",
        "enabled-importers": enabled_importers,
    }
    if not dry_run:
        write_json(apps_json, out)
        log(f"Wrote {len(merged_apps)} apps ({len(plan['kept_foreign'])} not ours, left alone). "
            f"Enabled importers: {', '.join(enabled_importers) or 'none'}")

    if as_json:
        # Logs go to stderr, so stdout stays a clean JSON document.
        doc = plan_document(plan, config_dir=conf_dir, apps_json=apps_json,
                            sources=sources, dry_run=dry_run,
                            generator_version=VERSION)
        json.dump(doc, sys.stdout, indent=2)
        sys.stdout.write("\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
